### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by reefki** [ueberdosis/tiptap-php#25] opened 2022-06-29 07:16 UTC
Hi there,

Silly question but when I trying to get JSON from the following HTML, it throws `Array to string conversion in ../vendor/ueberdosis/tiptap-php/src/Core/DOMParser.php on line 144`.

```
<p><iframe frameborder="0" height="385" src="https://www.youtube.com/embed/xxx" width="590"></iframe></p>
<p><iframe frameborder="0" height="385" src="https://www.youtube.com/embed/yyy" width="590"></iframe></p>
```

**Comment by anonim1133** [comment] 2022-07-20 11:51
Have you been able to find out what was the reason of that? Have you got it fixed?

**Comment by robertdrakedennis** [comment] 2022-08-27 23:27
ive also started having this issue, no real leads on whats causing it, i was migrating away from the deprecated tiptap parser but i definitely cant unless i get more info on how this is occuring

**Comment by Somethingideally** [comment] 2022-09-10 08:13
Same issue

**Comment by scottmetoyer** [comment] 2023-02-12 23:34
I'm also experiencing this issue.

**Comment by marvinosswald** [comment] 2023-05-31 08:27
Very weird, happens to me on production but not locally same php version tho.

PHP: 8.2.5

**Comment by godismyjudge95** [comment] 2023-10-01 04:06
I just encountered this while attempting to import content from WordPress - it wraps everything in p tags.

Submitted a PR with a failing test, so hopefully it gets merged soon 🤞

**Comment by enkay** [comment] 2024-03-11 21:59
I'm also getting this error while parsing html, no idea what's triggering it.

On version 1.3.0

**Comment by marvinosswald** [comment] 2024-05-03 07:06
@enkay I'm now quite certain this is caused by the `p` tag surrounding the image.

**Closed** 2024-08-12 08:07 UTC
